spring:
  application:
    name: architecture
  h2:
    console:
      enabled: true
      path: /hhplus-w2
  datasource:
    url: jdbc:h2:mem:hhplus-w2
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

